name: Python

on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:
    branches: [main]

permissions:
  contents: read

env:
  PYTHONUNBUFFERED: 1

jobs:
  pre-commit:
    name: Rerun pre-commit checks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.2
  tests:
    name: Tests
    needs: pre-commit
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.7, 3.8, 3.9, "3.10"]
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      id: setup-python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
    - name: Install OpenSlide
      run: |
        case "${{ matrix.os }}" in
        ubuntu-latest)
          sudo apt-get install libopenslide0
          ;;
        macos-latest)
          brew install openslide
          ;;
        esac
    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v2
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
    - name: Install dependencies
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      run: poetry install --no-interaction --no-root
    - name: Install openslide-python
      run: poetry install --no-interaction
    - name: Run tests
      run: poetry run pytest -v tests/
    - name: Tile slide
      run: poetry run examples/deepzoom/deepzoom_tile.py --viewer -o tiled tests/small.svs
  windows:
    name: Windows
    needs: pre-commit
    # test_read_bad_associated_image crashes with "Windows fatal exception:
    # code 0x80000003" on 64-bit windows-2022.  It probably doesn't help
    # that we're using an OpenSlide and library stack from 2017, compiled
    # with a 2017 compiler.  Pin to windows-2019 for now.
    runs-on: windows-2019
    env:
      WINBUILD_RELEASE: 20171122
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10"]
        python-arch: [x86, x64]
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }} ${{ matrix.python-arch }}
      id: setup-python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.python-arch }}
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
    - name: Install OpenSlide
      run: |
        case "${{ matrix.python-arch }}" in
        x86) zipname=openslide-win32-${WINBUILD_RELEASE} ;;
        x64) zipname=openslide-win64-${WINBUILD_RELEASE} ;;
        esac
        mkdir -p c:\\openslide
        cd c:\\openslide
        curl -LO "https://github.com/openslide/openslide-winbuild/releases/download/v${WINBUILD_RELEASE}/${zipname}.zip"
        7z x ${zipname}.zip
        echo "OPENSLIDE_PATH=c:\\openslide\\${zipname}\\bin" >> $GITHUB_ENV
    - name: Load cached venv
      id: cached-pip-wheels
      uses: actions/cache@v2
      with:
        path: ~/.cache
        key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
    - name: Build wheel
      run: |
        poetry build -f wheel
        basename=openslide-python-wheels-$GITHUB_RUN_NUMBER-$(echo $GITHUB_SHA | cut -c-10)
        mkdir -p "artifacts/${basename}"
        mv dist/*.whl "artifacts/${basename}"
        echo "basename=${basename}" >> $GITHUB_ENV
    - name: Install dependencies
      run: poetry install --no-interaction --no-root
    - name: Install openslide-python
      run: poetry install --no-interaction
    - name: Run tests
      # Reads OPENSLIDE_PATH
      run: poetry run pytest -v
    - name: Test library loading in examples
      # Reads OPENSLIDE_PATH
      run: |
        source $VENV
        examples/deepzoom/deepzoom_multiserver.py -h >/dev/null
        examples/deepzoom/deepzoom_server.py -h >/dev/null
        examples/deepzoom/deepzoom_tile.py -h >/dev/null
    - name: Tile slide
      # Reads OPENSLIDE_PATH
      run: |
        source $VENV
        examples/deepzoom/deepzoom_tile.py --viewer -o tiled tests/small.svs
    - name: Archive wheel
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.basename }}
        path: artifacts
  docs:
    name: Docs
    needs: pre-commit
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Set up Python
      id: setup-python
      uses: actions/setup-python@v2
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v2
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
    - name: Install dependencies
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      run: poetry install --no-interaction --no-root
    - name: Install openslide-python
      run: poetry install --no-interaction
    - name: Build
      run: |
        basename=openslide-python-docs-$GITHUB_RUN_NUMBER-$(echo $GITHUB_SHA | cut -c-10)
        poetry run sphinx-build -d doctrees doc artifact/${basename}
        echo "basename=${basename}" >> $GITHUB_ENV
    - name: Archive
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.basename }}
        path: artifact
